[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\x7f\0\0\x2\x87\0\0\0\0\0\0\0\0\0\0\x4\x7f\0\0\x2\x87\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x4\x7f\0\0\x2\x87)

[Appearance]
color_scheme_path=~/.config/qt6ct/colors/noctalia.conf
custom_palette=true
