palette = "noctalia"

# Don't print a new line at the start of the prompt
add_newline = false
format = """
$cmd_duration $directory$git_branch
  $character"""

[fill]
symbol = '-'
style = 'fg:245'

[character]
success_symbol = "[ ](bold fg:green)"
error_symbol = "[ ](bold fg:red)"

[package]
disabled = true

[git_branch]
style = "bg: blue"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = " 󰜥 [](bold fg:blue)[$symbol $branch(:$remote_branch)](fg:black bg:blue)[ ](bold fg:blue)"

[line_break]
disabled = false

[directory]
home_symbol = " "
read_only = "  "
style = "bg:yellow fg:black"
truncation_length = 2
truncation_symbol = ".../"
format = '[](bold fg:yellow)[󰉋 → $path]($style)[](bold fg:yellow)'


[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "
"Projects" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:blue)[󰪢 $duration](bold bg:blue fg:black)[](bold fg:blue)'

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#c0cc9a"
red       = "#ffb4ab"
green     = "#fdb975"
yellow    = "#e1c1a4"
cyan      = "#e1c1a4"
magenta   = "#fdb975"
white     = "#efe0d5"
black     = "#51453a"

# Extended palette (Catppuccin-compatible names)
rosewater = "#e1c1a4"
flamingo  = "#ffb4ab"
pink      = "#fdb975"
mauve     = "#fdb975"
maroon    = "#ffb4ab"
peach     = "#e1c1a4"
teal      = "#e1c1a4"
sky       = "#e1c1a4"
sapphire  = "#c0cc9a"
lavender  = "#fdb975"

# Text shades
text      = "#efe0d5"
subtext1  = "#efe0d5"
subtext0  = "#9d8e81"

# Surface shades
overlay2  = "#9d8e81"
overlay1  = "#9d8e81"
overlay0  = "#51453a"
surface2  = "#51453a"
surface1  = "#51453a"
surface0  = "#19120c"
base      = "#19120c"
mantle    = "#19120c"
crust     = "#19120c"
# <<< NOCTALIA STARSHIP PALETTE <<<
