palette = "noctalia"

# Don't print a new line at the start of the prompt
add_newline = false
format = """
$cmd_duration $directory$git_branch
  $character"""

[fill]
symbol = '-'
style = 'fg:245'

[character]
success_symbol = "[ ](bold fg:green)"
error_symbol = "[ ](bold fg:red)"

[package]
disabled = true

[git_branch]
style = "bg: blue"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = " 󰜥 [](bold fg:blue)[$symbol $branch(:$remote_branch)](fg:black bg:blue)[ ](bold fg:blue)"

[line_break]
disabled = false

[directory]
home_symbol = " "
read_only = "  "
style = "bg:yellow fg:black"
truncation_length = 2
truncation_symbol = ".../"
format = '[](bold fg:yellow)[󰉋 → $path]($style)[](bold fg:yellow)'


[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "
"Projects" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:blue)[󰪢 $duration](bold bg:blue fg:black)[](bold fg:blue)'

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#f0b2ef"
red       = "#ffb4ab"
green     = "#afc6ff"
yellow    = "#bdc6e2"
cyan      = "#bdc6e2"
magenta   = "#afc6ff"
white     = "#e3e2e7"
black     = "#444650"

# Extended palette (Catppuccin-compatible names)
rosewater = "#bdc6e2"
flamingo  = "#ffb4ab"
pink      = "#afc6ff"
mauve     = "#afc6ff"
maroon    = "#ffb4ab"
peach     = "#bdc6e2"
teal      = "#bdc6e2"
sky       = "#bdc6e2"
sapphire  = "#f0b2ef"
lavender  = "#afc6ff"

# Text shades
text      = "#e3e2e7"
subtext1  = "#e3e2e7"
subtext0  = "#8e909b"

# Surface shades
overlay2  = "#8e909b"
overlay1  = "#8e909b"
overlay0  = "#444650"
surface2  = "#444650"
surface1  = "#444650"
surface0  = "#121317"
base      = "#121317"
mantle    = "#121317"
crust     = "#121317"
# <<< NOCTALIA STARSHIP PALETTE <<<
