[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

[theme.templates]
builtin_ids = ["btop", "cava", "gtk3", "gtk4", "hyprland", "kitty", "qt"]
community_ids = ["pywalfox", "vscode", "discord"]
enable_builtin_templates = true
enable_community_templates = true

[wallpaper]
directory = "/home/sbalghari/Pictures/Wallpapers"
edge_smoothness = 0.3
enabled = true
fill_color = ""
fill_mode = "crop"
per_monitor_directories = false
transition = ["fade", "wipe", "disc", "stripes", "zoom", "honeycomb"]
transition_duration = 1500.0
transition_on_startup = true

[wallpaper.automation]
enabled = false
interval_seconds = 1800
order = "random"
recursive = true

[control_center]
sidebar = "compact"
sidebar_section = "none"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[dock]
enabled = false
