[widget.active_window]
icon_size = 14.0
max_length = 260.0
min_length = 0
title_scroll = "none"
type = "active_window"

[widget.battery]
scale = 1.1500000000000001
show_label = false
type = "battery"

[widget.bluetooth]
hide_when_no_connected_device = true
type = "bluetooth"

[widget.brightness]
show_label = false
type = "brightness"

[widget.clock]
capsule = true
capsule_border = "outline"
capsule_fill = "primary"
capsule_foreground = "on_surface"
capsule_opacity = 0.3
font_weight = 500
format = "{:%I:%M %p}"
scale = 1.15
tooltip_format = "{:%d  %A,  %B  %Y}"
type = "clock"

[widget.control-center]
custom_image_colorize = true
type = "control-center"

[widget.cpu]
stat = "cpu_usage"
type = "sysmon"

[widget.date]
format = "{:%a %d %b}"
type = "clock"

[widget.input_volume]
device = "input"
type = "volume"

[widget.keyboard_layout]
cycle_command = ""
hide_when_single_layout = false
type = "keyboard_layout"

[widget.lock_keys]
display = "short"
hide_when_off = false
show_caps_lock = true
show_num_lock = true
show_scroll_lock = false
type = "lock_keys"

[widget.media]
art_size = 20.0
hide_when_no_media = true
max_length = 220.0
min_length = 0
title_scroll = "on_hover"
type = "media"

[widget.network]
scale = 1.2
show_label = false
type = "network"

[widget.network_rx]
stat = "net_rx"
type = "sysmon"

[widget.network_tx]
stat = "net_tx"
type = "sysmon"

[widget.notifications]
hide_when_no_unread = true
type = "notifications"

[widget.output_volume]
device = "output"
type = "volume"

[widget.ram]
stat = "ram_used"
type = "sysmon"

[widget.temp]
stat = "cpu_temp"
type = "sysmon"

[widget.tray]
drawer = true
drawer_columns = 5
pinned = ["Vesktop"]
type = "tray"

[widget.volume]
scroll_step = 2
show_label = false
type = "volume"

[widget.workspaces]
capsule_radius = "auto"
font_weight = 700
type = "workspaces"

[desktop_widgets]
enabled = true
schema_version = 2

[desktop_widgets.grid]
cell_size = 16
major_interval = 4
visible = true
